### ISSUE TITLE
pip install fails: no README.rst

### ISSUE THREAD

**Issue by yrizk** [jtleider/censusdata#1]
This is the error message i get when 
>Collecting censusdata
  Using cached CensusData-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/21/klwvzx956qg2wyh1dtnd86fw00bgqc/T/pip-build-y2g9v4d3/censusdata/setup.py", line 7, in <module>
        long_description=open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

pip 9.0.1
python 3.6 (also fails on 2.7)

**Comment by jtleider** [comment]
Fixed MANIFEST.in to include README.rst. Also fixed format of python_requires in setup.py. Tested install, now works.
